deployment:
  tasks:
    - export PATH={/opt/homebrew/bin/node}:$PATH
    - export DEPLOYPATH=/home/eaasynmb/public_html/
    - /bin/cp -r * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install
    - npm run start
